# workflow名称
name: Deploy to Production  

# 触发workflow条件
on:
  push:
    branches:
      - build  # 触发部署的分支，可以根据需要修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检查
        uses: actions/checkout@v2

      - name: 安装依赖
        run: npm install

      - name: 构建next应用
        run: npm run build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v3
        with:
          branch: build
          folder: out
          clean: true
      # - name: Deploy to Production
      #   run: |
      #     # 这里写部署脚本，比如使用 FTP、SSH、或者其他自动化部署工具
      #     # 示例：使用 SSH 部署到服务器
      #     ssh user@your-server 'cd /path/to/your/app && git pull && npm install && npm run build'

      # # 可选：如果需要通知部署结果，可以添加通知步骤
      # # - name: Notify Deployment Status
      # #   run: echo "Deployment completed successfully"

# workflow: jobs -> steps -> actions
# jobs.<job_id>: name 任务名称, needs 依赖顺序， runs-on 运行所需虚拟机环境， steps 运行步骤
# steps: name 步骤名称，run 运行命令，env 环境变量
